version: "3.7"

services:
  redis:
    image: redis:alpine
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "8999:3306"
    environment:
      MYSQL_DATABASE: teviepe
      MYSQL_ROOT_PASSWORD: root
  server:
    image: teviepe-server
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
  web:
    image: teviepe-web
    ports:
      "3000:3000"