version: "3.7"

services:
  redis:
    image: redis:alpine
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "8999:3306"
    environment:
      MYSQL_DATABASE: teviepe_test
      MYSQL_ROOT_PASSWORD: root
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/teviepe-dev
      - /teviepe-dev/node_modules
    env_file:
      - ./server.env
    environment:
      REDIS: redis
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

volumes:
  mysqldata: